theme: jekyll-theme-minimal
title: Rohan Joshi | $ ./deploy-career.sh
description: 🚀 Rohan Joshi | DevOps Engineer ~ Automating infrastructure, optimizing pipelines, and deploying scalable solutions. $ cat portfolio.txt
